Angular points
freecodecamp-fresnoca/arthop-map-dev pull request #33
Opened 2016-11-26 04:49 UTC by Rawradin

I need to do some refactoring of the authentication middleware. I just copied it over to the venues route file just so I could build out the backend points feature.

2016-11-26 23:10 UTC, michaelachrisco requested changes
Good PR. Just push the user route methods into the user model or a middleware/service and I think we should be good.

2016-11-26 23:10 UTC, michaelachrisco commented on app/public/scripts/angular/panelStates/visited.js
> +      let percentage = user.points / venues.length
Nice!

2016-11-26 23:10 UTC, michaelachrisco commented on app/backend/routes/venues.js
> +function ensureAuthenticated(req, res, next) {
I would add this check into the users model in `../models/user.js` or as a `../services/user.js` and use the method as a service.

2016-11-26 23:10 UTC, michaelachrisco commented on app/backend/routes/venues.js
> +router.post('/verify',ensureAuthenticated, (req, res, next) => {
At this point, do you mind refactoring this method into own controller and documented. This route file is doing a bit too much and is going to cause future confusion. I believe you alluded a bit to this.

2016-11-26 23:15 UTC, michaelachrisco commented
As always @rick can override my opinion and merge, but I believe a small refactor needs to be done before this branch is merged. Not a huge deal but the route files are doing things the angular controllers should be doing.

Thanks for the PR @Rawradin! Just make those small changes and Ill merge.

2016-11-27 01:31 UTC, Rawradin commented
Refactored most of the addressed points but could use a second opinion on how to proceed with all the User updating points logic in /venues/verify route.

2016-11-27 06:33 UTC, rick commented
![](http://www.kickbright.net/photo2012/gbv5.gif)

2016-11-27 17:46 UTC, michaelachrisco commented
@Rawradin LGTM!

2016-11-27 17:46 UTC, merged